// FILE: ipcChannels.ts
// Purpose: Defines the data-only IPC channel contract shared by Electron main and preload.
// Layer: Desktop IPC contract

export const DESKTOP_IPC_CHANNELS = {
  pickFolder: "desktop:pick-folder",
  pickImage: "desktop:pick-image",
  saveFile: "desktop:save-file",
  confirm: "desktop:confirm",
  setTheme: "desktop:set-theme",
  setAppTheme: "desktop:set-app-theme",
  setAppTypography: "desktop:set-app-typography",
  setSpacesMenu: "desktop:set-spaces-menu",
  contextMenu: "desktop:context-menu",
  openExternal: "desktop:open-external",
  showInFolder: "desktop:show-in-folder",
  resourceOpen: "desktop:resource-open",
  resourceContextMenu: "desktop:resource-context-menu",
  clipboardWriteImage: "desktop:clipboard-write-image",
  windowMinimize: "desktop:window-minimize",
  windowToggleMaximize: "desktop:window-toggle-maximize",
  windowClose: "desktop:window-close",
  windowGetState: "desktop:window-get-state",
  windowState: "desktop:window-state",
  menuAction: "desktop:menu-action",
  updateState: "desktop:update-state",
  updateGetState: "desktop:update-get-state",
  updateCheck: "desktop:update-check",
  updateDownload: "desktop:update-download",
  updateInstall: "desktop:update-install",
  notificationsIsSupported: "desktop:notifications-is-supported",
  notificationsShow: "desktop:notifications-show",
  mediaRequestMicrophoneAccess: "desktop:media-request-microphone-access",
  powerSetActiveWork: "desktop:power-set-active-work",
  threadApiRequest: "desktop:thread-api-request",
  threadApiResponse: "desktop:thread-api-response",
  threadApiState: "desktop:thread-api-state",
  threadApiTurnOriginBind: "desktop:thread-api-turn-origin-bind",
  threadApiTurnOriginUnbind: "desktop:thread-api-turn-origin-unbind",
  composerDrafts: {
    readSnapshot: "desktop:composer-drafts-read-snapshot",
    writeSnapshot: "desktop:composer-drafts-write-snapshot",
    removeSnapshot: "desktop:composer-drafts-remove-snapshot",
    writeAsset: "desktop:composer-drafts-write-asset",
    readAsset: "desktop:composer-drafts-read-asset",
    deleteAsset: "desktop:composer-drafts-delete-asset",
    createVoice: "desktop:composer-drafts-create-voice",
    appendVoice: "desktop:composer-drafts-append-voice",
    completeVoice: "desktop:composer-drafts-complete-voice",
    listVoices: "desktop:composer-drafts-list-voices",
    readVoice: "desktop:composer-drafts-read-voice",
    deleteVoice: "desktop:composer-drafts-delete-voice",
    publishEditRecovery: "desktop:composer-drafts-publish-edit-recovery",
    editRecovery: "desktop:composer-drafts-edit-recovery",
  },
  accountAuth: {
    getState: "desktop:account-auth-get-state",
    requestSignIn: "desktop:account-auth-request-sign-in",
    requestSignUp: "desktop:account-auth-request-sign-up",
    signOut: "desktop:account-auth-sign-out",
    callbackStarted: "desktop:account-auth-callback-started",
    authenticated: "penkra-account:authenticated",
    userUpdated: "penkra-account:user-updated",
    error: "penkra-account:error",
  },
  zoomFactor: "desktop:zoom-factor",
  zoomFactorChanged: "desktop:zoom-factor-changed",
  wsUrl: "desktop:get-ws-url",
  voice: {
    capabilities: "desktop:voice-capabilities",
    transcribeWithApple: "desktop:voice-transcribe-with-apple",
    transcribeWithServer: "desktop:voice-transcribe-with-server",
  },
  storageMigration: {
    read: "desktop:storage-migration-read",
    acknowledge: "desktop:storage-migration-acknowledge",
  },
  appRuntime: {
    hostMessage: "penkra-app:host-message",
    event: "penkra-app:event",
    rendererMessage: "penkra-app:renderer-message",
    ready: "penkra-app:ready",
    call: "penkra-app:call",
    tabSetRoute: "penkra-app:tab-set-route",
    tabOpenSibling: "penkra-app:tab-open-sibling",
    tabGetContext: "penkra-app:tab-get-context",
    permissionQuery: "penkra-app:permission-query",
    permissionRequest: "penkra-app:permission-request",
    identityGet: "penkra-app:identity-get",
    identityGetToken: "penkra-app:identity-get-token",
    accountProfileGet: "penkra-app:account-profile-get",
    accountDataRequest: "penkra-app:account-data-request",
    accountDataSubscribeStart: "penkra-app:account-data-subscribe-start",
    accountDataSubscribeStop: "penkra-app:account-data-subscribe-stop",
    accountDataEvent: "penkra-app:account-data-event",
    settingGet: "penkra-app:setting-get",
    settingSet: "penkra-app:setting-set",
    settingReset: "penkra-app:setting-reset",
    secretGet: "penkra-app:secret-get",
    secretSet: "penkra-app:secret-set",
    secretDelete: "penkra-app:secret-delete",
    browserCall: "penkra-app:browser-call",
    simulatorCall: "penkra-app:simulator-call",
    networkFetch: "penkra-app:network-fetch",
    storageCall: "penkra-app:storage-call",
    threadCall: "penkra-app:thread-call",
  },
  simulatorLicenseReview: {
    response: "penkra-simulator-license-review:response",
  },
  appInstallations: {
    state: "desktop:app-installations-state",
    getState: "desktop:app-installations-get-state",
    installRegistry: "desktop:app-installations-install-registry",
    updateRegistry: "desktop:app-installations-update-registry",
    rollbackRegistry: "desktop:app-installations-rollback-registry",
    setEnabled: "desktop:app-installations-set-enabled",
    setPermission: "desktop:app-installations-set-permission",
    getSettings: "desktop:app-installations-get-settings",
    setSetting: "desktop:app-installations-set-setting",
    resetSetting: "desktop:app-installations-reset-setting",
    setSkillEnabled: "desktop:app-installations-set-skill-enabled",
    uninstall: "desktop:app-installations-uninstall",
    removeData: "desktop:app-installations-remove-data",
  },
  appRegistry: {
    list: "desktop:app-registry-list",
    get: "desktop:app-registry-get",
    getArtifact: "desktop:app-registry-get-artifact",
    getFeedback: "desktop:app-registry-get-feedback",
    setRating: "desktop:app-registry-set-rating",
    setReview: "desktop:app-registry-set-review",
  },
  appTabs: {
    listingRequested: "desktop:app-tabs-listing-requested",
    consumeListingRequest: "desktop:app-tabs-consume-listing-request",
    opened: "desktop:app-tabs-opened",
    state: "desktop:app-tabs-state",
    closed: "desktop:app-tabs-closed",
    presentation: "desktop:app-tabs-presentation",
    list: "desktop:app-tabs-list",
    open: "desktop:app-tabs-open",
    openFromApps: "desktop:app-tabs-open-from-apps",
    present: "desktop:app-tabs-present",
    hide: "desktop:app-tabs-hide",
    overlayActive: "desktop:app-tabs-overlay-active",
    setContext: "desktop:app-tabs-set-context",
    navigate: "desktop:app-tabs-navigate",
    close: "desktop:app-tabs-close",
  },
  appDiagnostics: {
    list: "desktop:app-diagnostics-list",
  },
  appOpenWith: {
    get: "desktop:app-open-with-get",
    set: "desktop:app-open-with-set",
  },
  browser: {
    requestOpenPanel: "desktop:browser-use-request-open-panel",
  },
} as const;

export const DESKTOP_WS_URL_CHANNEL = DESKTOP_IPC_CHANNELS.wsUrl;
export const APP_RUNTIME_IPC_CHANNELS = DESKTOP_IPC_CHANNELS.appRuntime;
