// FILE: ipcChannels.ts
// Purpose: Defines the data-only IPC channel contract shared by Electron main and preload.
// Layer: Desktop IPC contract

export const DESKTOP_IPC_CHANNELS = {
  pickFolder: "desktop:pick-folder",
  pickImage: "desktop:pick-image",
  saveFile: "desktop:save-file",
  confirm: "desktop:confirm",
  setTheme: "desktop:set-theme",
  setAppTheme: "desktop:set-app-theme",
  setAppTypography: "desktop:set-app-typography",
  setSpacesMenu: "desktop:set-spaces-menu",
  contextMenu: "desktop:context-menu",
  openExternal: "desktop:open-external",
  showInFolder: "desktop:show-in-folder",
  resourceOpen: "desktop:resource-open",
  resourceContextMenu: "desktop:resource-context-menu",
  clipboardWriteImage: "desktop:clipboard-write-image",
  windowMinimize: "desktop:window-minimize",
  windowToggleMaximize: "desktop:window-toggle-maximize",
  windowClose: "desktop:window-close",
  windowGetState: "desktop:window-get-state",
  windowState: "desktop:window-state",
  menuAction: "desktop:menu-action",
  updateState: "desktop:update-state",
  updateGetState: "desktop:update-get-state",
  updateCheck: "desktop:update-check",
  updateDownload: "desktop:update-download",
  updateInstall: "desktop:update-install",
  notificationsIsSupported: "desktop:notifications-is-supported",
  notificationsShow: "desktop:notifications-show",
  mediaRequestMicrophoneAccess: "desktop:media-request-microphone-access",
  powerSetActiveWork: "desktop:power-set-active-work",
  composerStageRequest: "desktop:composer-stage-request",
  composerStageResponse: "desktop:composer-stage-response",
  composerDrafts: {
    readSnapshot: "desktop:composer-drafts-read-snapshot",
    writeSnapshot: "desktop:composer-drafts-write-snapshot",
    removeSnapshot: "desktop:composer-drafts-remove-snapshot",
    writeAsset: "desktop:composer-drafts-write-asset",
    readAsset: "desktop:composer-drafts-read-asset",
    deleteAsset: "desktop:composer-drafts-delete-asset",
    createVoice: "desktop:composer-drafts-create-voice",
    appendVoice: "desktop:composer-drafts-append-voice",
    completeVoice: "desktop:composer-drafts-complete-voice",
    listVoices: "desktop:composer-drafts-list-voices",
    readVoice: "desktop:composer-drafts-read-voice",
    deleteVoice: "desktop:composer-drafts-delete-voice",
  },
  accountAuth: {
    getState: "desktop:account-auth-get-state",
    requestSignIn: "desktop:account-auth-request-sign-in",
    requestSignUp: "desktop:account-auth-request-sign-up",
    signOut: "desktop:account-auth-sign-out",
    callbackStarted: "desktop:account-auth-callback-started",
    authenticated: "penkra-account:authenticated",
    userUpdated: "penkra-account:user-updated",
    error: "penkra-account:error",
  },
  zoomFactor: "desktop:zoom-factor",
  zoomFactorChanged: "desktop:zoom-factor-changed",
  wsUrl: "desktop:get-ws-url",
  voice: {
    capabilities: "desktop:voice-capabilities",
    transcribeWithApple: "desktop:voice-transcribe-with-apple",
    transcribeWithServer: "desktop:voice-transcribe-with-server",
  },
  storageMigration: {
    read: "desktop:storage-migration-read",
    acknowledge: "desktop:storage-migration-acknowledge",
  },
  appRuntime: {
    hostMessage: "penkra-app:host-message",
    rendererMessage: "penkra-app:renderer-message",
    ready: "penkra-app:ready",
    tabSetRoute: "penkra-app:tab-set-route",
    tabGetContext: "penkra-app:tab-get-context",
    permissionQuery: "penkra-app:permission-query",
    permissionRequest: "penkra-app:permission-request",
    identityGet: "penkra-app:identity-get",
    identityGetToken: "penkra-app:identity-get-token",
    accountDataRequest: "penkra-app:account-data-request",
    accountDataSubscribeStart: "penkra-app:account-data-subscribe-start",
    accountDataSubscribeStop: "penkra-app:account-data-subscribe-stop",
    accountDataEvent: "penkra-app:account-data-event",
    settingGet: "penkra-app:setting-get",
    settingSet: "penkra-app:setting-set",
    settingReset: "penkra-app:setting-reset",
    secretGet: "penkra-app:secret-get",
    secretSet: "penkra-app:secret-set",
    secretDelete: "penkra-app:secret-delete",
    browserCall: "penkra-app:browser-call",
    browserState: "penkra-app:browser-state",
    browserDownload: "penkra-app:browser-download",
    simulatorCall: "penkra-app:simulator-call",
    simulatorState: "penkra-app:simulator-state",
    networkFetch: "penkra-app:network-fetch",
    storageCall: "penkra-app:storage-call",
    composerStage: "penkra-app:composer-stage",
  },
  simulatorLicenseReview: {
    response: "penkra-simulator-license-review:response",
  },
  appInstallations: {
    state: "desktop:app-installations-state",
    getState: "desktop:app-installations-get-state",
    installRegistry: "desktop:app-installations-install-registry",
    updateRegistry: "desktop:app-installations-update-registry",
    rollbackRegistry: "desktop:app-installations-rollback-registry",
    setEnabled: "desktop:app-installations-set-enabled",
    setPermission: "desktop:app-installations-set-permission",
    getSettings: "desktop:app-installations-get-settings",
    setSetting: "desktop:app-installations-set-setting",
    resetSetting: "desktop:app-installations-reset-setting",
    setSkillEnabled: "desktop:app-installations-set-skill-enabled",
    uninstall: "desktop:app-installations-uninstall",
    removeData: "desktop:app-installations-remove-data",
  },
  appRegistry: {
    list: "desktop:app-registry-list",
    get: "desktop:app-registry-get",
    getArtifact: "desktop:app-registry-get-artifact",
    getFeedback: "desktop:app-registry-get-feedback",
    setRating: "desktop:app-registry-set-rating",
    setReview: "desktop:app-registry-set-review",
  },
  appTabs: {
    listingRequested: "desktop:app-tabs-listing-requested",
    consumeListingRequest: "desktop:app-tabs-consume-listing-request",
    opened: "desktop:app-tabs-opened",
    state: "desktop:app-tabs-state",
    closed: "desktop:app-tabs-closed",
    list: "desktop:app-tabs-list",
    open: "desktop:app-tabs-open",
    openFromApps: "desktop:app-tabs-open-from-apps",
    setActive: "desktop:app-tabs-set-active",
    frameCall: "desktop:app-tabs-frame-call",
    frameMessage: "desktop:app-tabs-frame-message",
    frameReady: "desktop:app-tabs-frame-ready",
    frameHostMessage: "desktop:app-tabs-frame-host-message",
    browserWebviewAttach: "desktop:app-tabs-browser-webview-attach",
    browserWebviewDidFailLoad: "desktop:app-tabs-browser-webview-did-fail-load",
    browserWebviewDetach: "desktop:app-tabs-browser-webview-detach",
    browserHostedPageBounds: "desktop:app-tabs-browser-hosted-page-bounds",
    navigate: "desktop:app-tabs-navigate",
    close: "desktop:app-tabs-close",
  },
  appDiagnostics: {
    list: "desktop:app-diagnostics-list",
  },
  appOpenWith: {
    get: "desktop:app-open-with-get",
    set: "desktop:app-open-with-set",
  },
  browser: {
    requestOpenPanel: "desktop:browser-use-request-open-panel",
  },
} as const;

export const DESKTOP_WS_URL_CHANNEL = DESKTOP_IPC_CHANNELS.wsUrl;
export const APP_RUNTIME_IPC_CHANNELS = DESKTOP_IPC_CHANNELS.appRuntime;
