/** Stable v1 incident codes from docs/diagnostics-design.md. */
export const INCIDENT_CODES = [
  "SEND_PREFLIGHT_REJECTED",
  "WS_NOT_CONNECTED",
  "COMMAND_REJECTED",
  "TURN_START_TIMEOUT",
  "TURN_OUTPUT_SILENT",
  "STOP_NOT_EFFECTIVE",
  "PROVIDER_INTERRUPT_FAILED",
  "PLAY_REJECTED",
  "QUEUE_STALLED",
  "QUEUE_ORDER_VIOLATION",
  "COMMAND_DISPATCH_TIMEOUT",
  "LOCK_WAIT_EXCEEDED",
  "PROVIDER_START_TIMEOUT",
  "DELIVERY_BLOCKED",
  "INTENT_QUARANTINED",
  "PROVIDER_CALL_FAILED",
  "PROVIDER_CALL_SLOW",
  "PROVIDER_EVENT_DECODE_FAILED",
  "PROVIDER_RUNTIME_JOURNAL_DRAIN_FAILED",
  "WS_HANDSHAKE_SLOW",
  "WS_RECONNECT_LOOP",
  "REJECTED_STREAMING_RPC_ADMISSION",
  "SYNC_ACK_STALE",
  "CALLER_TURN_INACTIVE",
  "SCOPE_DENIED",
  "MCP_TIMEOUT",
  "TURN_STATE_DIVERGED",
  "INVARIANT_VIOLATED",
  "RECOVERY_PERFORMED",
  "ARCHIVE_REFUSED_RUNNING",
  "ARCHIVED_THREAD_STILL_OPEN",
  "CREATE_TIMEOUT",
  "CREATE_COMPENSATED",
  "ROUTE_TARGET_MISSING",
  "RENDERER_UNRESPONSIVE",
  "RENDERER_CRASHED",
  "AUTH_FAILED",
  "TOKEN_REFRESH_FAILED",
  "UPDATE_CHECK_FAILED",
  "UPDATE_DOWNLOAD_FAILED",
  "UPDATE_VERIFY_FAILED",
  "UPDATE_INSTALL_FAILED",
  "DB_BUSY",
  "DB_WRITE_FAILED",
  "DB_MIGRATION_FAILED",
  "DB_MAINTENANCE_SLOW",
  "APP_OPERATION_FAILED",
  "APP_TIMEOUT",
  "BOOT_SLOW",
  "UNCLEAN_SHUTDOWN",
  "PROCESS_UNRESPONSIVE",
  "PROCESS_CRASHED",
  "EXPECTATION_MISSED",
  "DIAGNOSTICS_DROPPED",
  "DIAGNOSTICS_WRITE_FAILED",
  "DIAGNOSTICS_CAP_REACHED",
  "EXTERNAL_CALL_FAILED",
  "EXTERNAL_CALL_SLOW",
] as const;

export type IncidentCode = (typeof INCIDENT_CODES)[number];
/** Reviewed, content-free sentences. No input data is interpolated. */
export const INCIDENT_SUMMARIES: Record<IncidentCode, string> = {
  SEND_PREFLIGHT_REJECTED: "Send preflight was rejected.",
  WS_NOT_CONNECTED: "Ws not connected was detected.",
  COMMAND_REJECTED: "Command was rejected.",
  TURN_START_TIMEOUT: "Turn start timed out.",
  TURN_OUTPUT_SILENT: "Turn output silent was detected.",
  STOP_NOT_EFFECTIVE: "Stop not effective was detected.",
  PROVIDER_INTERRUPT_FAILED: "Provider interrupt failed.",
  PLAY_REJECTED: "Play was rejected.",
  QUEUE_STALLED: "Queue stalled.",
  QUEUE_ORDER_VIOLATION: "Queue order violation was detected.",
  COMMAND_DISPATCH_TIMEOUT: "Command dispatch timed out.",
  LOCK_WAIT_EXCEEDED: "Lock wait exceeded was detected.",
  PROVIDER_START_TIMEOUT: "Provider start timed out.",
  DELIVERY_BLOCKED: "Delivery blocked was detected.",
  INTENT_QUARANTINED: "Intent quarantined was detected.",
  PROVIDER_CALL_FAILED: "Provider call failed.",
  PROVIDER_CALL_SLOW: "Provider call was slow.",
  PROVIDER_EVENT_DECODE_FAILED: "Provider event decode failed.",
  PROVIDER_RUNTIME_JOURNAL_DRAIN_FAILED: "Provider runtime journal drain failed.",
  WS_HANDSHAKE_SLOW: "Ws handshake was slow.",
  WS_RECONNECT_LOOP: "Ws reconnect loop was detected.",
  REJECTED_STREAMING_RPC_ADMISSION: "Rejected streaming rpc admission was detected.",
  SYNC_ACK_STALE: "Sync ack stale was detected.",
  CALLER_TURN_INACTIVE: "Caller turn inactive was detected.",
  SCOPE_DENIED: "Scope denied was detected.",
  MCP_TIMEOUT: "Mcp timed out.",
  TURN_STATE_DIVERGED: "Turn state diverged was detected.",
  INVARIANT_VIOLATED: "Invariant violated was detected.",
  RECOVERY_PERFORMED: "Recovery performed was detected.",
  ARCHIVE_REFUSED_RUNNING: "Archive refused running was detected.",
  ARCHIVED_THREAD_STILL_OPEN: "Archived thread still open was detected.",
  CREATE_TIMEOUT: "Create timed out.",
  CREATE_COMPENSATED: "Create compensated was detected.",
  ROUTE_TARGET_MISSING: "Route target missing was detected.",
  RENDERER_UNRESPONSIVE: "Renderer unresponsive was detected.",
  RENDERER_CRASHED: "Renderer crashed.",
  AUTH_FAILED: "Auth failed.",
  TOKEN_REFRESH_FAILED: "Token refresh failed.",
  UPDATE_CHECK_FAILED: "Update check failed.",
  UPDATE_DOWNLOAD_FAILED: "Update download failed.",
  UPDATE_VERIFY_FAILED: "Update verify failed.",
  UPDATE_INSTALL_FAILED: "Update install failed.",
  DB_BUSY: "Db busy was detected.",
  DB_WRITE_FAILED: "Db write failed.",
  DB_MIGRATION_FAILED: "Db migration failed.",
  DB_MAINTENANCE_SLOW: "Db maintenance was slow.",
  APP_OPERATION_FAILED: "App operation failed.",
  APP_TIMEOUT: "App timed out.",
  BOOT_SLOW: "Boot was slow.",
  UNCLEAN_SHUTDOWN: "Unclean shutdown was detected.",
  PROCESS_UNRESPONSIVE: "Process unresponsive was detected.",
  PROCESS_CRASHED: "Process crashed.",
  EXPECTATION_MISSED: "Expectation missed was detected.",
  DIAGNOSTICS_DROPPED: "Diagnostics dropped was detected.",
  DIAGNOSTICS_WRITE_FAILED: "Diagnostics write failed.",
  DIAGNOSTICS_CAP_REACHED: "Diagnostics cap reached was detected.",
  EXTERNAL_CALL_FAILED: "External call failed.",
  EXTERNAL_CALL_SLOW: "External call was slow.",
};
const codes = new Set<string>(INCIDENT_CODES);

export function isIncidentCode(value: string): value is IncidentCode {
  return codes.has(value);
}
